spring.application.name=master2


server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/master2
spring.datasource.username=postgres
spring.datasource.password=passer
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true



